### ISSUE TITLE
proper format for URL query params

### ISSUE THREAD

**Issue by ddaugher** [weareyipyip/Phoenix-API-Toolkit#35]
cannot figure out the proper format for the query params in order to get the 'order_by' functionality to work.

**Comment by juulSme** [comment]
Hi! You can use `PhoenixApiToolkit.Ecto.Validators.validate_order_by/2` to parse query params of the format `"direction:field"`. You need to use an Ecto changeset to process your query params. 

You can also take a look at https://hexdocs.pm/phoenix_api_toolkit/PhoenixApiToolkit.GenericRequestValidator.html for some help in the docs. That module does have some issues (the `to_tuple/1` stuff for example, and the schema format) that we would like to address but we will respect semantic versioning and it shouldn't break.
