### ISSUE TITLE
Improve sets

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [weareyipyip/Phoenix-API-Toolkit#39]
`sets` query filter is not expanded in total cases.

It works if we search a single role, but not if we search all users for multiple roles.
In this case the query looks like:
```elixir
:roles, ["root", "managers"]
```

So a it requires to add in the query filter generator:
```elixir
{key, value}, query when is_list(key) -> ... where: user.role in ^value
{key, value}, query  -> ... where: user.role == ^value
```

**Comment by juulSme** [comment]
Support for set membership / intersection / subsets will be added in 1.x.x after merging #34. For now, as documented, only set-membership of a single value is supported.
